---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    app: nginx
spec:
  storageClassName: "local"
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  local:
    path: /k8s/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
  capacity:
   storage: 1Gi