name: CI

on:
  push:
    branches:
      - 'v1'
    paths:
      - 'static/**'
  workflow_dispatch:
    inputs:
      job:
        description: 'Deploy to the environment'
        required: true
        default: 'deploy-prod'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Assign variables from file to Env variable
        run: |
            cat env/default/variables >> $GITHUB_ENV
      - name: Declare git branch and sha
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check branch and sha
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_PASSWORD != '' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image
        run: |
          ./build.sh -b ${{ steps.vars.outputs.sha_short }}

      - name: Test docker container 
        run: |
          ./build.sh -t ${{ steps.vars.outputs.sha_short }}
      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ steps.vars.outputs.sha_short }}
          args: --file=./Dockerfile
            --severity-threshold=high
          sarif: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Build for multiplatform
        env: 
          image_tag: ${{ steps.vars.outputs.sha_short }}
        run: |
          docker buildx build \
            --push \
            --platform=linux/amd64,linux/arm64,linux/386 \
            --tag=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.image_tag }} .
  deploy-prod:
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - name: Manual approve for deployment
      uses: trstringer/manual-approval@v1
      env: 
          image_tag: ${{ steps.vars.outputs.sha_short }}
      with:
        secret: ${{ github.TOKEN }}
        approvers: mustafaerbay
        minimum-approvals: 1
        issue-title: "Deploying image_tag"
        run: echo deploying

    - uses: actions/checkout@v2
    - name: Run Kubernetes tools
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.23.0
        kustomize: 4.4.1
        helm: 2.17.0
        helmv3: 3.7.2
        kubeseal: 0.16.0
        kubeval: v0.16.1
        conftest: 0.28.3
        kubeconform: 0.4.12
        command: |
          echo "Run conftest"